export const people = [
  {
    id: 1,
    title: "Trustee",
    name: "Ayo Adesanya",
    email: "ayo@stopholdingback.com",
    image: "https://i.imgur.com/FRIs3ds.png?1",
    website: "http://www.ayoadesanya.com",
    linkedin: "https://www.linkedin.com/in/ayoadesanya/",
    instagram: "https://www.instagram.com/ayo.stopholdingback/",
    twitter: "https://twitter.com/Ayo__Codes",
  },

  {
    id: 2,
    title: "Trustee",
    name: "Chris Jackson",
    email: "cj@stopholdingback.com",
    image: "https://i.imgur.com/KfrhNKl.png",
    website: "",
    linkedin: "",
    instagram: "",
    twitter: "",
  },

  {
    id: 3,
    title: "Trustee",
    name: "Ruban Pillai",
    email: "ruban@stopholdingback.com",
    image: "https://i.imgur.com/yYI0g50.png",
    website: "",
    linkedin: "",
    instagram: "",
    twitter: "",
  },
  {
    id: 4,
    title: "Trustee",
    name: "James Redhead",
    email: "ruban@stopholdingback.com",
    image: "https://i.imgur.com/7506LkW.png",
    website: "",
    linkedin: "",
    instagram: "",
    twitter: "",
  },
  {
    id: 5,
    title: "Mentor",
    name: "Callum Schofiled",
    email: "ruban@stopholdingback.com",
    image: "https://imgur.com/RBIBQ6t.png",
    website: "",
    linkedin: "",
    instagram: "",
    twitter: "",
  },
];
